"""add billing active to subscriptions

Revision ID: 133af708bb2a
Revises: 515d8242f3e1
Create Date: 2026-05-11 16:26:21.655464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133af708bb2a'
down_revision: Union[str, Sequence[str], None] = '515d8242f3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_billable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_billable')
    # ### end Alembic commands ###
