"""add invoice counters table

Revision ID: 2480ded4cc50
Revises: e858bc2d0a1b
Create Date: 2026-04-21 11:53:20.024736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2480ded4cc50'
down_revision: Union[str, Sequence[str], None] = 'e858bc2d0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_counters',
    sa.Column('period_key', sa.String(length=6), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('period_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_counters')
    # ### end Alembic commands ###
