"""add usage record non-negative check

Revision ID: 3d4121d3f7b3
Revises: 8187820a1e40
Create Date: 2026-04-22 13:35:38.232636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4121d3f7b3'
down_revision: Union[str, Sequence[str], None] = '8187820a1e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_usage_records_active_user_count_non_negative",
        "usage_records",
        "active_user_count >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_usage_records_active_user_count_non_negative",
        "usage_records",
        type_="check",
    )
    # ### end Alembic commands ###
