"""add invoice item duplicate protection

Revision ID: 515d8242f3e1
Revises: 3d4121d3f7b3
Create Date: 2026-04-27 10:22:35.487759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515d8242f3e1'
down_revision: Union[str, Sequence[str], None] = '3d4121d3f7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_invoice_items_subscription_type_period', 'invoice_items', ['subscription_id', 'item_type', 'period_start', 'period_end'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoice_items_subscription_type_period', 'invoice_items', type_='unique')
    # ### end Alembic commands ###
