"""add usage records table

Revision ID: 8187820a1e40
Revises: 2480ded4cc50
Create Date: 2026-04-22 12:57:16.965846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8187820a1e40'
down_revision: Union[str, Sequence[str], None] = '2480ded4cc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('subscription_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('active_user_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'recorded_on', name='uq_usage_records_subscription_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_records')
    # ### end Alembic commands ###
