"""add nullable False next billing date to subscriptions

Revision ID: 9956599c20b2
Revises: b24f88845458
Create Date: 2026-04-07 20:39:50.540910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9956599c20b2'
down_revision: Union[str, Sequence[str], None] = 'b24f88845458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'next_billing_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'next_billing_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
