"""update invoices and invoice items

Revision ID: 9a71249d6981
Revises: ef138778a3dd
Create Date: 2026-03-31 13:34:16.115580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a71249d6981'
down_revision: Union[str, Sequence[str], None] = 'ef138778a3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('subscription_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('invoice_items', sa.Column('item_type', sa.String(length=50), nullable=False))
    op.add_column('invoice_items', sa.Column('period_start', sa.DateTime(), nullable=True))
    op.add_column('invoice_items', sa.Column('period_end', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'invoice_items', 'subscriptions', ['subscription_id'], ['id'])
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('invoices', sa.Column('billing_period_start', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('billing_period_end', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('issued_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('voided_at', sa.DateTime(), nullable=True))
    op.drop_column('invoices', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('invoices', 'voided_at')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'issued_at')
    op.drop_column('invoices', 'billing_period_end')
    op.drop_column('invoices', 'billing_period_start')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'subtotal')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'period_end')
    op.drop_column('invoice_items', 'period_start')
    op.drop_column('invoice_items', 'item_type')
    op.drop_column('invoice_items', 'subscription_id')
    # ### end Alembic commands ###
