"""add next billing date to subscriptions

Revision ID: b24f88845458
Revises: 8f4a6884bb4a
Create Date: 2026-04-07 16:21:17.310797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24f88845458'
down_revision: Union[str, Sequence[str], None] = '8f4a6884bb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('next_billing_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'next_billing_date')
    # ### end Alembic commands ###
