"""add overage user pricing

Revision ID: e858bc2d0a1b
Revises: ec6e25050f40
Create Date: 2026-04-20 11:43:12.037935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e858bc2d0a1b'
down_revision: Union[str, Sequence[str], None] = 'ec6e25050f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('overage_user_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('subscriptions', sa.Column('overage_user_price_override', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'overage_user_price_override')
    op.drop_column('plans', 'overage_user_price')
    # ### end Alembic commands ###
