"""add price to subscriptions

Revision ID: ec6e25050f40
Revises: 9956599c20b2
Create Date: 2026-04-14 11:34:28.108366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec6e25050f40'
down_revision: Union[str, Sequence[str], None] = '9956599c20b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('subscriptions', 'user_quota_override',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'user_quota_override',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###
